//GLOBAL
export const TOGGLE_LOADING ="TOGGLE_LOADING";
export const IS_SUBMITED  ="IS_SUBMITED";
export const IS_ERROR  ="IS_ERROR";
//USER
export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const SET_USER = "SET_USER"
export const LOGOUT_USER = "LOGOUT_USER"